name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt install libboost-all-dev

      - name: Run tests
        run: make run_tests

      - name: Install gcovr
        run: sudo apt install -y gcovr

      - name: Generate coverage report
        run: make coverage_xml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
