name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: sudo apt install libboost-all-dev

      - name: Run tests
        run: make run_tests
